### ISSUE TITLE
Issue with default value of merchant_name in DocdataOrder model

### ISSUE THREAD

**Issue by mj026** [edoburu/django-oscar-docdata#1]
Hello.

In the `DocdataOrder`, the merchant_name is defined as following:

`
merchant_name = models.CharField(_("Docdata account"), max_length=100, default=appsettings.DOCDATA_MERCHANT_NAME)
`

When you use the `oscar_docdata` package and set the `DOCDATA_MERCHANT_NAME` in your settings.py, the migration framework of Django will detect a change and creates a new migration for this (in the docdata package which is installed as an egg). I'm not sure what is the best way to solve this problem, @vdboor maybe you have some suggestions?

**Comment by vdboor** [comment]
What I've done in other projects, is using the `appsettings.DOCDATA_MERCHANT_NAME` variable in the migrations too. However, it could lead to database inconsistencies if you change it. I'm open for a pull request that makes sure the value is set without relying on the `default=` attribute

**Comment by mj026** [comment]
@vdboor What do you mean with "using the appsettings.DOCDATA_MERCHANT_NAME variable in the migrations too"? Did you create a custom migration yourself or?

**Comment by vdboor** [comment]
There you go: 539ef9da4d6e2c10f840cc7f3dbac5545262e5e9
This is released as 1.2.9
