### ISSUE TITLE
Recurring payment

### ISSUE THREAD

**Issue by rahilwazir** [edoburu/django-oscar-docdata#2]
Does DocData API supports recurring payment? If so, what are the required parameters?

Sorry, this issue is not related to this project/repo honestly but because of the limited documentation/resources out there, just wanna know.

**Comment by vdboor** [comment]
Judging from their site, some of their payment methods support it.
I also noticed Adyen supports recurring payments, and I have a much better experience working with them compared to Docdata. See these notes too: https://github.com/edoburu/django-oscar-docdata#caveats Adyen on the other hand, worked flawless on international payments and address fields.
