### ISSUE TITLE
django reload problems...

### ISSUE THREAD

**Issue by jedie** [edoburu/django-oscar-docdata#20]
from: https://github.com/django-oscar/django-oscar-docdata/issues/14#issuecomment-459345049

> Suds is doing some dynamic magic when parsing the WSDL so it could be that the auto-reloading of the Django development server (manage.py runserver) is causing this.

What's about to skip the suds client cache in testing mode? Maybe that can help here?

Maybe something like this: https://github.com/wearehoods/django-oscar-docdata/commit/08edee0b090dc62729251ead9238d610429f9a4d

**Comment by mj026** [comment]
Could help, but it seems like the problems are gone now right?

**Comment by jedie** [comment]
Or there was no problem with reloading?
