### ISSUE TITLE
Update to DocData v1.3

### ISSUE THREAD

**Issue by jedie** [edoburu/django-oscar-docdata#21]
Isn't it a good idea to update?

**Comment by jedie** [comment]
Hm. I looked at a diff between `xsd1-1_2.xsd` and `xsd1-1_3.xsd` ... there are many changes.

Think it would probably be easier to get v1.2 running first and then update to v1.3 later.

**Comment by mj026** [comment]
In a customer project we are already using 1.3 so when we have a working release with 1.2 it would be an idea to focus on a 1.3 release indeed

**Comment by mj026** [comment]
Merged  #30

**Comment by mj026** [comment]
Released in version 1.3.0

**Comment by jedie** [comment]
Great work!

**Comment by mj026** [comment]
@jedie Thank you for your contributions!
