### ISSUE TITLE
skip own payment method view

### ISSUE THREAD

**Issue by jedie** [edoburu/django-oscar-docdata#37]
(from #34)

> > One more question: In the sandbox the payment method is asked in the "checkout wizard" ... It should be possible to move that into the docdata Payment Page, isn't it? How to do this?
> 
> You should skip this view then and I think you can ask for the menu without any default pm (then docdata will show the available options):
> 
> ```python
> url = facade.get_payment_menu_url(self.request, docdata_ref)
> ```

What's about a settings variable to skip the payment method step?

**Comment by mj026** [comment]
Here you go: https://github.com/django-oscar/django-oscar-docdata/commit/7552af4984ebfe3a403e6839719ff0c2ad27d59c

**Comment by jedie** [comment]
Great!
