### ISSUE TITLE
DocdataOrder status="finished"

### ISSUE THREAD

**Issue by jedie** [edoburu/django-oscar-docdata#48]
```
class DocdataOrder(models.Model):
    ...
    STATUS_NEW = 'new'                      # Initial state
    STATUS_IN_PROGRESS = 'in_progress'      # In the redirect phase
    STATUS_PENDING = 'pending'              # Waiting for user to complete payment (e.g. credit cards)
    STATUS_PAID = 'paid'                    # End of story, paid!
    STATUS_PAID_REFUNDED = 'paid_refunded'  # Paid, and performed a partial refund
    STATUS_CANCELLED = 'cancelled'          # End of story, cancelled
    STATUS_CHARGED_BACK = 'charged_back'    # End of story, consumer asked for charge back
    STATUS_REFUNDED = 'refunded'            # End of story, refunded, merchant refunded
    STATUS_EXPIRED = 'expired'              # No results of customer, order was closed.
    STATUS_UNKNOWN = 'unknown'              # Help!
    ...
```

I missed here a status for a completely finished order. A order that was paid and shipped.

I have this information indirectly in "status" from: `oscar.apps.order.models.Order`

**Comment by mj026** [comment]
`shipped` (fulfilment) is not part  of the Docdata payment API as far a I know (and it shouldn't be)

**Comment by jedie** [comment]
It's more about keeping internal records when the order it's done.
But then maybe `oscar.apps.order.models.Order` is the best.

**Comment by mj026** [comment]
Yes, Oscar orders should have statuses like 'shipped' / 'dispatched', 'delivered' or whatever status you need in your particular use-case. So after the order is paid, another process should take care of the correct status of the oscar orders.

A Docdata order is just representing an order inside the Docdata payments environment.

**Comment by jedie** [comment]
Yeah, you're right. I think that's enough. I'm closing here.
