### ISSUE TITLE
Add tests (at least some functional tests)

### ISSUE THREAD

**Issue by jedie** [edoburu/django-oscar-docdata#7]
It seems that there a no tests, no CI etc. isn't it?!?

Maybe run tests against the "sandbox" ?

**Comment by mj026** [comment]
Me too. I'll be working the following weeks to upgrade a project to python 3 which is using this package. I try to add a testrunner as well and some basic tests

**Comment by mj026** [comment]
`travis ci` is now configured and a basic functional test for the checkout flow has now been added.
See also https://travis-ci.org/django-oscar/django-oscar-docdata
